spring:
  application:
    name: dos-wrapper

server:
  port: 7030
  ssl:
    key-store: /keystore.jks
    key-store-password: changeit
    keyStoreType: PKCS12
    keyAlias: capacityservice

# URL prefix (after domain, before Servlet)
cxf:
  path: "/nhsd/doswrapper/ws"

dos:
  service:
    url: DummyValue

# Spring Boot Actuator configuration
endpoints:
  metrics:
    enabled: false
  auditevents:
    enabled: false
  info:
    enabled: false
  mappings:
    enabled: false
  beans:
    enabled: false
  loggers:
    enabled: false
  dump:
    enabled: false
  heapdump:
    enabled: false
  health:
    enabled: true
    id: health
    path: /healthcheck
    sensitive: false
  env:
    enabled: false
  configprops:
    enabled: false
  autoconfig:
    enabled: false
  trace:
    enabled: false